Repository Som-Energia/webforms-ui, pull requests merged in 2024-07, with the labels that each got.

#95 🐛 add vat validation
  src/containers/HolderChange.jsx
Labels: enhancement

#96 🧹 Remove avis autonom
  CHANGES.md
  src/containers/ModifyContract.jsx
  src/i18n/locale-ca.json
  src/i18n/locale-es.json
  src/i18n/locale-eu.json
  src/i18n/locale-gl.json
Labels: show

#93 New autocomplete address
  .env
  package.json
  src/components/AddressAutocompletedField.jsx
  src/containers/Contract.jsx
  src/containers/Contract/SupplyPoint.jsx
  src/services/googleApiClient.js
Labels: enhancement

#98 Fix form validations
  src/components/Chooser.jsx
  src/components/StateCity.jsx
  src/containers/Contract.jsx
  src/containers/Contract/CUPS.jsx
  src/containers/Contract/HolderIdentifier.jsx
  src/containers/Contract/PowerFare.jsx
  src/containers/Contract/SelfConsumption.jsx
  src/containers/Contract/SelfConsumptionDetails.jsx
  src/containers/Contract/SupplyPoint.jsx
  src/containers/Contract/TariffMode.jsx
  src/containers/Contribution/MemberIdentifier.jsx
  src/containers/Generation/GenerationForm/GenerationMemberIdentifier.jsx
  src/containers/HolderChange/BecomeMember.jsx
  src/containers/HolderChange/VoluntaryCent.jsx
  src/containers/ModifyContract/Params.jsx
  src/services/utils.js
Labels: bug
